providers = []

[phases.setup]
  nixPkgs = ['(sbt.override { jre = jdk8; })', 'openjdk8-bootstrap']

[phases.build]
  cmds = ['sbt stage']
  dependsOn = ['setup']

[start]
  runImage = 'eclipse-temurin:8u432-b06-jre'
